version: '3'
services:
  docker-watcher:
    build: .
    container_name: docker-watcher
    hostname: docker-watcher
    environment:
      DOCKER_REGISTRY: "${DOCKER_REGISTRY}"
      DOCKER_PRUNE: "${DOCKER_PRUNE}"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped